version: '2'
services:
    bugreader-app:
        image: bugreader
        external_links:
            - bugreader-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=bugreader
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bugreader-mongodb:
        extends:
            file: mongodb.yml
            service: bugreader-mongodb
