version: '2'
services:
    bukreader-app:
        image: bukreader
        external_links:
            - bukreader-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Bukreader
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bukreader-mongodb:
        extends:
            file: mongodb.yml
            service: bukreader-mongodb
