version: '2'
services:
    bukreader-mongodb:
        container_name: bukreader-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/Bukreader/mongodb/:/data/db/
